# Generated by Django 4.0 on 2022-01-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_qty',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
