# Generated by Django 4.0 on 2022-01-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_alter_tax_tax_rate_alter_unit_unit_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_qty',
        ),
    ]
