# Generated by Django 4.0 on 2022-01-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_remove_tax_tax_rate_remove_unit_unit_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
