# Generated by Django 4.0 on 2022-01-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_tax_tax_rate_unit_unit_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='created',
            field=models.CharField(default='already', max_length=50),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_qty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
