# Generated by Django 4.0 on 2022-01-07 11:22

from django.db import migrations, models
import selling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=10, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('group_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('group_unit_qty', models.IntegerField(blank=True, null=True)),
                ('stock_qty', models.IntegerField(blank=True, null=True)),
                ('alert_qty', models.IntegerField(blank=True, null=True)),
                ('cost_price', models.IntegerField(blank=True, null=True)),
                ('tax_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_rate', models.IntegerField(blank=True, null=True)),
                ('purchased_price', models.IntegerField(blank=True, null=True)),
                ('tax_type', models.CharField(blank=True, max_length=50, null=True)),
                ('profit_margin', models.IntegerField(blank=True, null=True)),
                ('sales_price', models.IntegerField(blank=True, null=True)),
                ('final_price', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('featured_image', models.FileField(blank=True, null=True, upload_to=selling.models.featured_item_image)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
