# Generated by Django 4.0 on 2022-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_client_alter_item_cost_price_alter_item_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='client',
            name='whatsappNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
