# Generated by Django 4.0 on 2022-01-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_remove_client_whatsapp_client_whatsappno'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
