# Generated by Django 4.0 on 2022-01-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0005_alter_client_openingbalance_alter_client_returndues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='adjust_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='-'),
        ),
    ]
