# Generated by Django 4.0 on 2022-01-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0008_item_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group_unit_qty',
            field=models.IntegerField(default=1),
        ),
    ]
