# Generated by Django 4.0 on 2022-01-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0010_invoice_address_invoice_city_invoice_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
