# Generated by Django 4.0 on 2022-01-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0012_alter_invoice_whatsapp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='walk_in_client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
