# Generated by Django 4.0 on 2022-01-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0013_invoice_bill_file_invoice_walk_in_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='whatsappNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
