# Generated by Django 4.0 on 2022-01-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0014_alter_client_whatsappno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='adjust_stock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='item',
            name='qty_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
