# Generated by Django 4.0 on 2022-01-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0015_remove_item_adjust_stock_remove_item_expired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='alert_qty',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
