# Generated by Django 4.0 on 2022-01-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0016_alter_item_alert_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchased_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
