# Generated by Django 4.0 on 2022-01-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0017_alter_item_cost_price_alter_item_purchased_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='profit_margin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
