# Generated by Django 4.0 on 2022-01-31 11:33

from django.db import migrations, models
import selling.models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0020_alter_client_salesdues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=selling.models.bill_image),
        ),
    ]
