# Generated by Django 4.0 on 2022-01-31 14:17

from django.db import migrations, models
import selling.models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0021_alter_invoice_bill_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='billFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField(blank=True, null=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to=selling.models.bill_image)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bill_file',
        ),
    ]
