# Generated by Django 4.0 on 2022-01-31 15:02

from django.db import migrations, models
import selling.models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0022_billfile_remove_invoice_bill_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=selling.models.bill_image),
        ),
    ]
