# Generated by Django 4.0 on 2022-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0023_invoice_bill_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='billfile',
            name='whatsappNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
