# Generated by Django 4.0 on 2022-02-02 08:40

from django.db import migrations, models
import selling.models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0024_billfile_whatsappno'),
    ]

    operations = [
        migrations.CreateModel(
            name='quoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.IntegerField(blank=True, null=True)),
                ('quote_file', models.FileField(blank=True, null=True, upload_to=selling.models.quote_image)),
                ('whatsappNo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
