# Generated by Django 4.0 on 2022-02-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0025_quotefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
