# Generated by Django 4.0 on 2022-02-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0026_invoice_item_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qty_sold',
            field=models.IntegerField(default=0),
        ),
    ]
