# Generated by Django 4.0 on 2022-01-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
