# Generated by Django 4.0 on 2022-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('whatsappNo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('openingBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('salesDues', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('returnDues', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
