# Generated by Django 4.0 on 2022-02-01 16:28

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.IntegerField(blank=True, null=True)),
                ('purchase_file', models.FileField(blank=True, null=True, upload_to=management.models.purchase_image)),
                ('whatsappNo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
