# Generated by Django 4.0 on 2022-02-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_purchasefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
